### ISSUE TITLE
Сохранение файла

### ISSUE THREAD

**Issue by vldmkrsh** [letulip/ScreenCapture#3]
Написать код программы, которая при запуске создаёт файл `hello.txt` с текстом внутри `Hello, World!`. После этого она завершает свою работу. 

Если файл существует, то она его перезаписывает.

**Comment by letulip** [comment]
Написал программу, создается директория на диске С:, в которой создается файл Hello.txt.
Хотел добавить создание ярлыка директории на рабочий стол для удобства пользования, но какая-то внутренняя ошибка студии не дает этого сделать.

**Comment by vldmkrsh** [comment]
А зачем тебе директория, когда мы создаём файл на рабочем столе?

**Comment by letulip** [comment]
Попробую еще раз: какая-то внутренняя ошибка не дает обращаться к рабочему столу, пока не разобрался в проблеме.
Директория нужна на диске С:, потому что туда будут складываться скрины, а на рабочем столе будет просто ярлык. Мне показалось, что так будет лучше.
Переделать на рабочий стол смогу когда решу проблему.

**Comment by vldmkrsh** [comment]
Пример сохранения файла на рабочий стол — http://stackoverflow.com/a/22205810/1806198

**Comment by letulip** [comment]
это плохой пример, так как у каждого пользователя свой путь к столу, есть специальная директива для сохранения на рабочий стол независимо от пути.

**Comment by letulip** [comment]
Я все починил, по моей схеме сейчас работает, думаю - это шаг вперед. Теперь я умею создавать ярлыки на рабочем столе. Могу переделать на просто создание файла на рабочем столе.

**Comment by vldmkrsh** [comment]
Надо переделать, такая задача.

**Comment by letulip** [comment]
Есть сохранение на рабочий стол.
