### ISSUE TITLE
Так вроде снимки экрана нужны!

### ISSUE THREAD

**Issue by vldmkrsh** [letulip/ScreenCapture#6]
Вместо текстового файла, надо сохранить снимок всего рабочего стола в формате `png`.

Название файла может быть `Screen Shot 2016-10-10 at 9.22.09 PM.png` для 12 часового отображения, либо используй 24 часовое отображение.

**Comment by letulip** [comment]
Есть снимки экрана на рабочий стол =))

**Comment by letulip** [comment]
В смарт гите я разобрался ОК! Все слито и в мастере, но проблем!
