### ISSUE TITLE
Кажется время потеряли?

### ISSUE THREAD

**Issue by vldmkrsh** [letulip/ScreenCapture#9]
Текущая реализация сохраняет в файл `Print of screen №1.png` для одного снимка, а эталонный вариант другой. Мы же делаем много снимков экрана, и не хотим, чтобы они перезаписывались. 

Для одного экрана он будет `Screen Shot 2016-12-04 at 14.20.08.png`, а для двух экранов соответственно `Screen Shot 2016-12-04 at 14.20.08 1.png` и `Screen Shot 2016-12-04 at 14.20.08 2.png`.

Делаем в ветке `lost-time`.

**Comment by vldmkrsh** [comment]
Я понял, ты формат немного другой выбрал. 

Проблема вся в том, что в твоём варианте сортировать файлы неудобно. Они будут путаться, если у тебя больше одного экрана.

**Comment by letulip** [comment]
Print of screen №1 yyyy-dd-mm.png
Print of screen №2 yyyy-dd-mm.png
Print of screen №3 yyyy-dd-mm.png
Я проверил, все ок

**Comment by vldmkrsh** [comment]
А теперь сделай 10 таких снимков, и после этого открой рабочий стол в проводнике. Посмотри, как он отсортирует __по имени__?

**Comment by letulip** [comment]
Понял, пофиксил, в новом патче выкачу.

**Comment by vldmkrsh** [comment]
Правильно делать отдельную ветку, а не выкатывать с чем-то другим. Не ленись. Из-за таких мелочей и выбирают одни приложения вместо других.

**Comment by letulip** [comment]
учту!

**Comment by vldmkrsh** [comment]
Внимание вопрос — зачем ты делаешь замену в строке пути, когда можно просто сделать конкатенацию?

**Comment by letulip** [comment]
мне показалось, что так удобнее.
